name = "Jallocator"
uuid = "43a00f91-a958-4379-a491-35c8b4c56136"
authors = ["Claudio Contardo <claudio.contardo@concordia.ca>"]
version = "0.1.0"

[deps]
StrideArrays = "d1fa6d79-ef01-42a6-86c9-f7c551f8593b"
StrideArraysCore = "7792a7ef-975c-4747-a70f-980b88e8d1da"

[compat]
StrideArrays = "0.1.28"
StrideArraysCore = "0.5.7"
